default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
        args:
          - -l 120
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --ignore=E203,W503
        stages:
          - commit
          - push

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        stages:
          - commit
          - push

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-docstring-first
        stages:
          - commit
          - push
      - id: check-merge-conflict
        stages:
          - push
      - id: trailing-whitespace
        stages:
          - commit
          - push
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.svg$
