// This file is auto-generated by @hey-api/openapi-ts

export const $Body_upload_photo_upload_photo_post = {
    properties: {
        photo: {
            type: 'string',
            format: 'binary',
            title: 'Photo'
        },
        photo_link: {
            type: 'string',
            title: 'Photo Link'
        },
        release_date: {
            type: 'string',
            title: 'Release Date'
        }
    },
    type: 'object',
    required: ['photo', 'photo_link', 'release_date'],
    title: 'Body_upload_photo_upload_photo_post'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $LinksSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        path: {
            type: 'string',
            title: 'Path'
        }
    },
    type: 'object',
    required: ['id', 'url', 'type', 'path'],
    title: 'LinksSchema'
} as const;

export const $SiteInfoEdit = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'SiteInfoEdit'
} as const;

export const $SiteInfoPlayWidget = {
    properties: {
        title: {
            type: 'string',
            title: 'Название карточки'
        },
        description: {
            type: 'string',
            title: 'Описание карточки'
        },
        color: {
            type: 'string',
            title: 'Цвет текста на карточке'
        },
        color_card: {
            type: 'string',
            title: 'Цвет карточки'
        },
        url: {
            type: 'string',
            title: "Ссылка при клике на 'Добавить в спотифай'"
        },
        button_name: {
            type: 'string',
            title: "Надпись на кнопке 'Добавить в спотифай'",
            default: 'Добавить в спотифай'
        },
        photo_path: {
            type: 'string',
            title: 'Ссылка на картинку'
        },
        song_source: {
            type: 'string',
            title: 'Ссылка на просшивание'
        }
    },
    type: 'object',
    required: ['title', 'description', 'color', 'color_card', 'url', 'photo_path', 'song_source'],
    title: 'SiteInfoPlayWidget'
} as const;

export const $SiteInfoSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Название сайта'
        },
        description: {
            type: 'string',
            title: 'Описание сайта'
        },
        year: {
            type: 'integer',
            title: 'Год сайта',
            default: 2024
        },
        links: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/LinksSchema'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Список ссылок сайта'
        },
        play_widget: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SiteInfoPlayWidget'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Виджет для получения проигрывателя'
        }
    },
    type: 'object',
    required: ['name', 'description'],
    title: 'SiteInfoSchema'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;
