// This file is auto-generated by @hey-api/openapi-ts

export const $Body_add_photo_api_v1_photos_post = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_add_photo_api_v1_photos_post'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $LinksSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        path: {
            type: 'string',
            title: 'Path'
        }
    },
    type: 'object',
    required: ['id', 'url', 'type', 'path'],
    title: 'LinksSchema'
} as const;

export const $PhotoAddSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        }
    },
    type: 'object',
    required: ['id', 'filename'],
    title: 'PhotoAddSchema'
} as const;

export const $PhotoListSchema = {
    properties: {
        photos: {
            items: {
                '$ref': '#/components/schemas/PhotoAddSchema'
            },
            type: 'array',
            title: 'Photos',
            default: []
        }
    },
    type: 'object',
    title: 'PhotoListSchema'
} as const;

export const $ReleasesSchema = {
    properties: {
        releases: {
            items: {
                '$ref': '#/components/schemas/ReleasesSchemaItem'
            },
            type: 'array',
            title: 'Releases',
            default: []
        }
    },
    type: 'object',
    title: 'ReleasesSchema'
} as const;

export const $ReleasesSchemaItem = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        file_id: {
            type: 'string',
            title: 'File Id'
        },
        link: {
            type: 'string',
            title: 'Link'
        }
    },
    type: 'object',
    required: ['id', 'created_at', 'updated_at', 'description', 'file_id', 'link'],
    title: 'ReleasesSchemaItem'
} as const;

export const $SiteInfoEdit = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'SiteInfoEdit'
} as const;

export const $SiteInfoPlayWidget = {
    properties: {
        title: {
            type: 'string',
            title: 'Название карточки'
        },
        description: {
            type: 'string',
            title: 'Описание карточки'
        },
        color: {
            type: 'string',
            title: 'Цвет текста на карточке'
        },
        color_card: {
            type: 'string',
            title: 'Цвет карточки'
        },
        url: {
            type: 'string',
            title: "Ссылка при клике на 'Добавить в спотифай'"
        },
        button_name: {
            type: 'string',
            title: "Надпись на кнопке 'Добавить в спотифай'",
            default: 'Добавить в спотифай'
        },
        photo_path: {
            type: 'string',
            title: 'Ссылка на картинку'
        },
        song_source: {
            type: 'string',
            title: 'Ссылка на просшивание'
        }
    },
    type: 'object',
    required: ['title', 'description', 'color', 'color_card', 'url', 'photo_path', 'song_source'],
    title: 'SiteInfoPlayWidget'
} as const;

export const $SiteInfoSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Название сайта'
        },
        description: {
            type: 'string',
            title: 'Описание сайта'
        },
        year: {
            type: 'integer',
            title: 'Год сайта',
            default: 2024
        },
        links: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/LinksSchema'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Список ссылок сайта'
        },
        play_widget: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SiteInfoPlayWidget'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Виджет для получения проигрывателя'
        }
    },
    type: 'object',
    required: ['name', 'description'],
    title: 'SiteInfoSchema'
} as const;

export const $VKIDFirstStepParams = {
    properties: {
        code_challenge: {
            type: 'string',
            title: 'Code Challenge'
        },
        code_challenge_method: {
            type: 'string',
            title: 'Code Challenge Method',
            default: 's256'
        },
        state: {
            type: 'string',
            title: 'State'
        },
        scopes: {
            type: 'string',
            title: 'Scopes',
            default: 'vkid.personal_info'
        },
        client_id: {
            type: 'string',
            title: 'Client Id'
        }
    },
    type: 'object',
    required: ['code_challenge', 'state', 'client_id'],
    title: 'VKIDFirstStepParams'
} as const;

export const $VKIDSecondStepParams = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        state: {
            type: 'string',
            title: 'State'
        },
        device_id: {
            type: 'string',
            title: 'Device Id'
        }
    },
    type: 'object',
    required: ['code', 'state', 'device_id'],
    title: 'VKIDSecondStepParams'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;
