// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ReadSiteInfoApiV1SiteInfoGetResponse, ChangeSiteInfoApiV1SiteInfoPostData, ChangeSiteInfoApiV1SiteInfoPostResponse, HomePageGetResponse, UploadFormUploadPhotoGetResponse, UploadPhotoUploadPhotoPostData, UploadPhotoUploadPhotoPostResponse, LoginFormLoginGetResponse, LoginLoginPostResponse } from './types.gen';

/**
 * Read Site Info
 * Return Site Links
 * @returns SiteInfoSchema Successful Response
 * @throws ApiError
 */
export const readSiteInfoApiV1SiteInfoGet = (): CancelablePromise<ReadSiteInfoApiV1SiteInfoGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/site_info'
}); };

/**
 * Change Site Info
 * Return changed information Links
 * @param data The data for the request.
 * @param data.requestBody
 * @returns SiteInfoEdit Successful Response
 * @throws ApiError
 */
export const changeSiteInfoApiV1SiteInfoPost = (data: ChangeSiteInfoApiV1SiteInfoPostData): CancelablePromise<ChangeSiteInfoApiV1SiteInfoPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/v1/site_info',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Home Page
 * @returns string Successful Response
 * @throws ApiError
 */
export const homePageGet = (): CancelablePromise<HomePageGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/'
}); };

/**
 * Upload Form
 * @returns string Successful Response
 * @throws ApiError
 */
export const uploadFormUploadPhotoGet = (): CancelablePromise<UploadFormUploadPhotoGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/upload_photo'
}); };

/**
 * Upload Photo
 * @param data The data for the request.
 * @param data.formData
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const uploadPhotoUploadPhotoPost = (data: UploadPhotoUploadPhotoPostData): CancelablePromise<UploadPhotoUploadPhotoPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/upload_photo',
    formData: data.formData,
    mediaType: 'multipart/form-data',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Login Form
 * @returns string Successful Response
 * @throws ApiError
 */
export const loginFormLoginGet = (): CancelablePromise<LoginFormLoginGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/login'
}); };

/**
 * Login
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const loginLoginPost = (): CancelablePromise<LoginLoginPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/login'
}); };
