// This file is auto-generated by @hey-api/openapi-ts

export type Body_upload_photo_upload_photo_post = {
    photo: (Blob | File);
    photo_link: string;
    release_date: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LinksSchema = {
    id: string;
    url: string;
    type: string;
    path: string;
};

export type SiteInfoEdit = {
    message: string;
};

export type SiteInfoPlayWidget = {
    title: string;
    description: string;
    color: string;
    color_card: string;
    url: string;
    button_name?: string;
    photo_path: string;
    song_source: string;
};

export type SiteInfoSchema = {
    name: string;
    description: string;
    year?: number;
    links?: Array<LinksSchema> | null;
    play_widget?: SiteInfoPlayWidget | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ReadSiteInfoApiV1SiteInfoGetResponse = SiteInfoSchema;

export type ChangeSiteInfoApiV1SiteInfoPostData = {
    requestBody: SiteInfoSchema;
};

export type ChangeSiteInfoApiV1SiteInfoPostResponse = SiteInfoEdit;

export type HomePageGetResponse = string;

export type UploadFormUploadPhotoGetResponse = string;

export type UploadPhotoUploadPhotoPostData = {
    formData: Body_upload_photo_upload_photo_post;
};

export type UploadPhotoUploadPhotoPostResponse = unknown;

export type LoginFormLoginGetResponse = string;

export type LoginLoginPostResponse = unknown;
